<?php
/**
 * @file field_tools.module
 * Contains useful tools for working with fields.
 */

/**
 * Implements hook_help().
 */
function field_tools_help($path, $arg) {
  // WTF: the $arg array is 12 items long with empty cruft at the end!?!
  $args_reverse = array_reverse(array_filter($arg));

  // Provide help for any path that ends in 'fields/%/clone'
  $last_three = array_slice(array_filter($arg), -3);
  // If we get fewer than three items we don't care anyway.
  if (count($last_three) >= 3) {
    if ($last_three[0] == 'fields' && $last_three[2] == 'clone') {
      return t('Apply this existing field to the other bundles by copying the current field instance.');
    }
  }

  // Provide help for any path that ends in 'fields-clone'
  if ($args_reverse[0] == 'fields-clone') {
    return t("Apply some or all fields of the current bundle to other bundles by copying the field instances.");
  }
}

/**
 * Implements hook_menu().
 */
function field_tools_menu() { 
  // Create tabs for all possible bundles.
  foreach (entity_get_info() as $entity_type => $entity_info) {
    if ($entity_info['fieldable']) {
      foreach ($entity_info['bundles'] as $bundle_name => $bundle_info) {
        if (isset($bundle_info['admin'])) {
          // Extract path information from the bundle.
          $path = $bundle_info['admin']['path'];
          // Different bundles can appear on the same path (e.g. %node_type and
          // %comment_node_type). To allow field_ui_menu_load() to extract the
          // actual bundle object from the translated menu router path
          // arguments, we need to identify the argument position of the bundle
          // name string ('bundle argument') and pass that position to the menu
          // loader. The position needs to be casted into a string; otherwise it
          // would be replaced with the bundle name string.
          if (isset($bundle_info['admin']['bundle argument'])) {
            $bundle_arg = $bundle_info['admin']['bundle argument'];
            $bundle_pos = (string) $bundle_arg;
          }
          else {
            $bundle_arg = $bundle_name;
            $bundle_pos = '0';
          }
          // This is the position of the %field_ui_menu placeholder in the
          // items below.
          $field_position = count(explode('/', $path)) + 1;

          // Extract access information, providing defaults.
          $access = array_intersect_key($bundle_info['admin'], drupal_map_assoc(array('access callback', 'access arguments')));
          $access += array(
            'access callback' => 'user_access',
            'access arguments' => array('administer site configuration'),
          );          

          // Menu item for cloning a bundle's fields en masse.
          // In some cases, $path is the same for every bundle, eg nodes, and
          // hence doing this here is redundant.
          $items["$path/fields-clone"] = array(
              'title' => 'Clone fields',
              'page callback' => 'drupal_get_form',
              'page arguments' => array('field_tools_bundle_fields_clone_form', $entity_type, (int) $bundle_pos),
              'type' => MENU_LOCAL_TASK,
              'file' => 'field_tools.admin.inc',
              'weight' => 10,
            ) + $access;

          // Menu item for cloning a single field.
          $items["$path/fields/%field_ui_menu/clone"] = array(
            'load arguments' => array($entity_type, $bundle_arg, $bundle_pos, '%map'),
            'title' => 'Clone',
            'page callback' => 'drupal_get_form',
            // The numeric $field_position gets us the field instance from the
            // %field_ui_menu menu loader.
            'page arguments' => array('field_tools_field_clone_form', $field_position),
            'type' => MENU_LOCAL_TASK,
            'file' => 'field_tools.admin.inc',
            'weight' => 10,
          ) + $access;
          
        }
      }
    }
  }

  return $items;
}
